### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by kthyng** [jmunroe/intake-erddap#1]
Hi! I'm looking into replacing some functionality with a few intake readers, including this one for ERDDAP. There are a few more things that I would need to add and possibly change, so I wanted to see what the current plan is for development, or if you're open to me adding and/or changing a few things. Happy to work together as much as possible! Thanks for this work! It's already useful to me.

**Comment by jmunroe** [comment]
Hi Kristen.  Honestly, I had forgotten I had even worked on this, so I have no current plans for developement. If it is at all useful to you, add/change as much as you like!

**Comment by kthyng** [comment]
Ok — should I just fork it over and go from there, or do you want to develop from here?

**Comment by jmunroe** [comment]
If you want to fork it/move it somewhere else, that probably makes more sense.

**Comment by kthyng** [comment]
Ok, thank you!
